services:
  - type: web
    name: geofencing-backend
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: SUPABASE_DB_URL
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
